---
- hosts: all
  become: yes
  tasks:
    - name: "Install EPEL-release"
      yum: 
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      tags: packages

    - name: "Install Python"
      yum: 
        name: python-pip
      tags: packages

    - name: "Install PostgreSQL"
      yum:
        name: 
          - postgresql
          - postgresql-server
          - python-psycopg2
      tags: packages

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service: name=postgresql state=started enabled=yes
    
    - name: "Create app database"
      postgresql_db:
        state: present
        name: "gitbucket"
      become: yes
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "gitbucket"
        password: "gitbucket"
      become: yes
      become_user: postgres

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "gitbucket"
        roles: "gitbucket"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "~/data/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "gitbucket"
        source: 0.0.0.0/0
        create: true
      become: yes
      become_user: postgres
      notify: restart postgres

    - name: "Set listen_address to *"
      lineinfile: 
        dest: /var/lib/pgsql/data/postgresql.conf
        regexp: "#listen_addresses = 'localhost'" 
        line: "listen_addresses = '*'" 
        state: present
      notify: restart postgres
      
    - name: "Set localhost connection to trust *"
      postgresql_pg_hba:
        dest: "~/data/pg_hba.conf"
        contype: local
        databases: all
        method: trust
        users: all
        state: present
      notify: restart postgres

    - name: "Create table in db"
      postgresql_table:
        db: gitbucket
        table: test
        columns:
        - id bigserial primary key
        - num int
        - data varchar(20)
    
    - name: "Open 5432/tcp port"
      firewalld:
        port: 5432/tcp
        permanent: yes
        state: enabled

    #- name: "Load SQL script into a variable"
     # set_fact:
      #  migration_sql: "{{ lookup('file', 'gitbucket.sql') }}"

    #- name: "Execute script from variable"
     # command: "psql gitbucket -c {{ migration_sql }}"
      #become_user: postgres
      #register: sql_response_variable
   
    - name: Install Bucardo dependencies
      yum:
        name: 
          - libboolean-perl
          - libdbd-pg-perl
          - postgresql-plperl-9.4
          - expect
        state: present
      tags: packages


    - name: Get dbix_safe
      get_url: 
        url: https://bucardo.org/downloads/dbix_safe.tar.gz 
        dest: /tmp/dbix_safe.tar.gz 
      tags: packages

    - name: Create temporary directory
      file: 
        state: directory
        path: /tmp/dbix
      tags: packages

    - name: Unarchive Dbix_safe
      unarchive:
        src: /tmp/dbix_safe.tar.gz
        dest: /tmp/dbix
        copy: no
      tags: packages

    - name: Build Dbix MakeFile
      shell: "perl Makefile.PL"
      args:
        chdir: /tmp/dbix/DBIx-Safe-1.2.5/
      tags: packages

    - name: Make Dbix
      shell: "make"
      args:
        chdir: /tmp/dbix/DBIx-Safe-1.2.5/
      tags: packages

    - name: Install Dbix
      shell: "sudo make install"
      args:
        chdir: /tmp/dbix/DBIx-Safe-1.2.5/
      tags: packages

    - name: Download Bucardo
      get_url:
        url: http://bucardo.org/downloads/Bucardo-5.3.1.tar.gz
        dest: /tmp/bucardo.tar.gz
      tags: packages

    - name: Create temporary directory
      file:
        state: directory
        path: /tmp/bucardo
      tags: packages

    - name: Unarchive Bucardo
      unarchive:
        src: /tmp/bucardo.tar.gz
        dest: /tmp/bucardo
        copy: no
      tags: packages

    - name: Build Bucardo Makefile
      shell: "perl Makefile.PL"
      args:
        chdir: /tmp/bucardo/Bucardo-5.3.1/
      tags: packages

    - name: Make Bucardo
      shell: "make"
      args:
        chdir: /tmp/bucardo/Bucardo-5.3.1/
      tags: packages

    - name: Install Bucardo
      shell: "sudo make install"
      args:
        chdir: /tmp/bucardo/Bucardo-5.3.1/
      tags: packages
      
    - name: Write install script
      copy:
        src: install.sh
        dest: "/tmp/install_bucardo.sh"
        owner: postgres
        mode: 0755

    - name: Create bucardo log directory
      file:
        state: directory
        path: /var/log/bucardo

    - name: Install Bucardo on the database
      shell: "sudo /tmp/install_bucardo.sh"
      
  
  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted



- hosts: db1
  become: yes
  tasks:
    - name: "Add local master db to Bucardo"
      shell: "bucardo add database db1 dbname=gitbucket host=localhost user=gitbucket password=gitbucket"
      
      

    - name: Add external  second master to Bucardo
      shell: "bucardo add database db2 dbname=gitbucket host= user=gitbucket dbpass=gitbucket"
      
      

    - name: Add tables to Bucardo
      shell: "bucardo add table all --db=db1 --herd=gitbucket_herd"
     
    
    - name: Add sequances to Bucardo
      shell: "bucardo add sequence all --db=db1 --herd=gitbucket_herd"
      

    - name: Create dbgroup
      shell: "bucardo add dbgroup gitbucket_group"
      

    - name: Add db1 as master
      shell: "bucardo add dbgroup gitbucket_group db1:source"
      
    
    - name: Add db2 as master
      shell: "bucardo add dbgroup gitbucket_group db2:source"
      

    - name: Add sync
      shell: "bucardo add sync gitbucket_sync herd=gitbucket_herd dbgroup=gitbucket_group"
      
    
    - name: Restart Bucardo
      shell: "bucardo restart"
      

    

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted

