---
- hosts: all
  become: yes
  tasks:
    - name: "Install repository package"
      yum: 
        state: present
        name: 
          - postgresql 
          - postgresql-contrib
          - postgresql-server
          - python-psycopg2
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service: name=postgresql state=started enabled=yes
    
    - name: "Create app database"
      postgresql_db:
        state: present
        name: "gitbucket"
      become: yes
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "gitbucket"
        password: "gitbucket"
      become: yes
      become_user: postgres

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "gitbucket"
        roles: "gitbucket"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

    - name: "Allow remote connection ipv4"
      ansible.buildin.lininfile: 
        path: "~/data/pg_hba.conf"
        search_string: '127.0.0.1/32' 
        line: 0.0.0.0/0
        owner: root
        group: root
        mode: '0644' 

    - name: "Allow remote connection ipv6"
      ansible.buildin.lininfile: 
        path: "~/data/pg_hba.conf"
        search_string: '::1/32' 
        line: ::0/0
        owner: root
        group: root
        mode: '0644' 

    - name: "Make md5 connection"
      ansible.buildin.lininfile: 
        path: "~/data/pg_hba.conf"
        search_string: 'ident' 
        line: md5
        owner: root
        group: root
        mode: '0644' 
        
    - name: "Allow remote connection ipv4"
      ansible.buildin.lininfile: 
        path: "~/data/postgresql.conf"
        search_string: '#listen_addresses="*"' 
        line: listen_addresses="*"
        owner: root
        group: root
        mode: '0644'     
   

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
