---
- hosts: all
  become: yes
  tasks:
    - name: "Install repository package"
      yum: 
        state: present
        name: 
          - postgresql 
          - postgresql-contrib
          - postgresql-server
          - python-psycopg2 
          
